"""table wishes

Revision ID: 0cbf34890d2c
Revises: 3b1c52f797da
Create Date: 2019-07-27 14:18:06.563029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cbf34890d2c'
down_revision = '3b1c52f797da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.Column('isbn', sa.String(length=15), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('gifts', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('gifts', sa.Column('given', sa.Boolean(), nullable=True))
    op.drop_constraint('gifts_ibfk_1', 'gifts', type_='foreignkey')
    op.drop_column('gifts', 'sent')
    op.drop_column('gifts', 'recipient_id')
    op.add_column('users', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_time')
    op.add_column('gifts', sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('gifts', sa.Column('sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('gifts_ibfk_1', 'gifts', 'users', ['recipient_id'], ['id'])
    op.drop_column('gifts', 'given')
    op.drop_column('gifts', 'created_time')
    op.drop_column('books', 'created_time')
    op.drop_table('wishes')
    # ### end Alembic commands ###
