"""empty message

Revision ID: 3b1c52f797da
Revises: 8ad5b97a53a3
Create Date: 2019-07-27 14:16:36.789853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1c52f797da'
down_revision = '8ad5b97a53a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('password_hash', sa.String(length=128), nullable=True)
    )
    op.alter_column('users', 'name', existing_type=sa.VARCHAR(length=24), nullable=True)
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(
        'users', 'name', existing_type=sa.VARCHAR(length=24), nullable=False
    )
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
