"""empty message

Revision ID: 3b1c52f797da
Revises: 8ad5b97a53a3
Create Date: 2019-07-27 14:16:36.789853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1c52f797da'
down_revision = '8ad5b97a53a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes')
    op.drop_column('books', 'created_time')
    op.drop_column('gifts', 'created_time')
    op.drop_column('gifts', 'given')
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.add_column('gifts', sa.Column('given', sa.BOOLEAN(), nullable=True))
    op.add_column('gifts', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.add_column('books', sa.Column('created_time', sa.DATETIME(), nullable=True))
    op.create_table('wishes',
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fulfilled', sa.BOOLEAN(), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=15), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('fulfilled IN (0, 1)'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
