"""float table

Revision ID: 4737209a64af
Revises: 6463d4d018c5
Create Date: 2019-08-06 16:14:15.280811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4737209a64af'
down_revision = '6463d4d018c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floats',
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('book_title', sa.String(length=50), nullable=True),
    sa.Column('book_author', sa.String(length=30), nullable=True),
    sa.Column('book_img', sa.String(length=140), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(length=24), nullable=True),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('giver_name', sa.String(length=24), nullable=True),
    sa.Column('transaction_status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('floats')
    # ### end Alembic commands ###
