"""rename field status as is_deleted

Revision ID: 6463d4d018c5
Revises: 0cbf34890d2c
Create Date: 2019-08-06 10:51:22.014297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6463d4d018c5'
down_revision = '0cbf34890d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_deleted', sa.SmallInteger(), nullable=False))
    op.alter_column('books', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('books', 'status')
    op.add_column('gifts', sa.Column('is_deleted', sa.SmallInteger(), nullable=False))
    op.alter_column('gifts', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('gifts', 'status')
    op.add_column('users', sa.Column('is_deleted', sa.SmallInteger(), nullable=False))
    op.alter_column('users', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('users', 'status')
    op.add_column('wishes', sa.Column('is_deleted', sa.SmallInteger(), nullable=False))
    op.alter_column('wishes', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('wishes', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.alter_column('wishes', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('wishes', 'is_deleted')
    op.add_column('users', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('users', 'is_deleted')
    op.add_column('gifts', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.alter_column('gifts', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('gifts', 'is_deleted')
    op.add_column('books', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.alter_column('books', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('books', 'is_deleted')
    # ### end Alembic commands ###
